[package]
name = "expert-system-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5", features=["json", "secrets"]}
diesel = { version = "2.1", features = ["postgres", "r2d2", "chrono", "serde_json"] }
chrono = { version = "0.4", features = ["serde"] }
dotenvy = "0.15"
serde = { version = "1.0", features = ["derive"] }
diesel-derive-enum = { version = "2.1", features = ["postgres"] }
validator = { version = "0.16", features = ["derive"] }

[dependencies.rocket_dyn_templates]
features = ["handlebars"]

[dependencies.rocket_contrib]
version = "0.4"
default-features = false
features = ["json"]
