//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, DeriveEntityModel, Eq, ToSchema)]
#[sea_orm(table_name = "attributesvalues")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub attribute_id: i32,
    pub value: String,
}

#[derive(Clone, Debug, Serialize, Deserialize, DeriveIntoActiveModel, ToSchema)]
pub struct UpdateAttributeValueModel {
    pub id: i32,
    pub value: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::attributes::Entity",
        from = "Column::AttributeId",
        to = "super::attributes::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Attributes,
    #[sea_orm(has_many = "super::object_attribute_attributevalue::Entity")]
    ObjectAttributeAttributevalue,
    #[sea_orm(has_many = "super::rule_attribute_attributevalue::Entity")]
    RuleAttributeAttributevalue,
}

impl Related<super::attributes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Attributes.def()
    }
}

impl Related<super::object_attribute_attributevalue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ObjectAttributeAttributevalue.def()
    }
}

impl Related<super::rule_attribute_attributevalue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RuleAttributeAttributevalue.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
