//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(
    Debug, Clone, Serialize, Deserialize, PartialEq, Eq, EnumIter, DeriveActiveEnum, ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "operatorenum")]
pub enum Operatorenum {
    #[sea_orm(string_value = "ABOVE")]
    Above,
    #[sea_orm(string_value = "BELOW")]
    Below,
    #[sea_orm(string_value = "EQUAL")]
    Equal,
    #[sea_orm(string_value = "NOT_EQUAL")]
    NotEqual,
    #[sea_orm(string_value = "NO_LESS_THAN")]
    NoLessThan,
    #[sea_orm(string_value = "NO_MORE_THAN")]
    NoMoreThan,
}
